"""P1-P4: QueueTask lang_override + QueueCoordinator + configure_and_run_queued + _start_pipeline overrides."""
import py_compile, shutil, tempfile, os

with open('manhwa_app/app.py', encoding='utf-8') as f:
    src = f.read()

assert '\r' not in src
print("Applying P1-P4...")

# P1
P1_OLD = ('                 voice_override: str = None, img_path: str = None):\n'
          '        self.project_name        = project_name\n'
          '        self.txt_path            = txt_path\n'
          '        self.mode                = mode\n'
          '        self.engine_override     = engine_override\n'
          '        self.model_type_override = model_type_override\n'
          '        self.voice_override      = voice_override\n'
          '        self.img_path            = img_path\n')
P1_NEW = ('                 voice_override: str = None, lang_override: str = None,\n'
          '                 img_path: str = None):\n'
          '        self.project_name        = project_name\n'
          '        self.txt_path            = txt_path\n'
          '        self.mode                = mode\n'
          '        self.engine_override     = engine_override\n'
          '        self.model_type_override = model_type_override\n'
          '        self.voice_override      = voice_override\n'
          '        self.lang_override       = lang_override\n'
          '        self.img_path            = img_path\n')
assert P1_OLD in src; src = src.replace(P1_OLD, P1_NEW, 1); print("P1 OK")

# P2: Replace QueueOrchestrator class
idx_orch = src.find('\nclass QueueOrchestrator(QThread):')
idx_dash_sep = src.find('\n# ---------------------------------------------------------------------------\n# Dashboard Tab', idx_orch)
assert idx_orch > 0 and idx_dash_sep > idx_orch

NEW_COORD = (
'\nclass QueueCoordinator(QObject):\n'
'    """Coordenador de fila event-driven. Usa o pipeline da aba Audio."""\n'
'    task_started  = Signal(int)\n'
'    task_progress = Signal(int, int, int)\n'
'    task_log      = Signal(int, str)\n'
'    task_finished = Signal(int, bool)\n'
'    queue_log     = Signal(str)\n'
'    all_done      = Signal()\n'
'\n'
'    def __init__(self, tasks: list, main_window, parent=None):\n'
'        super().__init__(parent)\n'
'        self.tasks       = list(tasks)\n'
'        self.main_window = main_window\n'
'        self._idx        = 0\n'
'        self._cancelled  = False\n'
'        self._audio_paths: list = []\n'
'\n'
'    def cancel(self):\n'
'        self._cancelled = True\n'
'        at = self.main_window.audio_tab\n'
'        if at._pipeline:\n'
'            at._pipeline.cancel()\n'
'\n'
'    def start(self):\n'
'        if not self.tasks:\n'
'            self.all_done.emit(); return\n'
'        self._idx = 0\n'
'        self._cancelled = False\n'
'        self._connect_audio()\n'
'        self._run_current()\n'
'\n'
'    def _connect_audio(self):\n'
'        at = self.main_window.audio_tab\n'
'        at.pipeline_progress.connect(self._on_progress)\n'
'        at.pipeline_log.connect(self._on_log)\n'
'        at.pipeline_finished.connect(self._on_audio_done)\n'
'        at.audio_generated.connect(self._on_generated)\n'
'\n'
'    def _disconnect_audio(self):\n'
'        at = self.main_window.audio_tab\n'
'        for sig, slot in [\n'
'            (at.pipeline_progress, self._on_progress),\n'
'            (at.pipeline_log,      self._on_log),\n'
'            (at.pipeline_finished, self._on_audio_done),\n'
'            (at.audio_generated,   self._on_generated),\n'
'        ]:\n'
'            try: sig.disconnect(slot)\n'
'            except: pass\n'
'\n'
'    def _run_current(self):\n'
'        if self._cancelled or self._idx >= len(self.tasks):\n'
'            self._finish(); return\n'
'        task = self.tasks[self._idx]\n'
'        task.status = "running"\n'
'        self.task_started.emit(self._idx)\n'
'        n = self._idx + 1; total = len(self.tasks)\n'
'        self.queue_log.emit(f"\\nProcessando [{n}/{total}] {task.project_name} ({task.mode_label()})")\n'
'        self.main_window.audio_tab.configure_and_run_queued(task)\n'
'\n'
'    @Slot(int, int)\n'
'    def _on_progress(self, current: int, total: int):\n'
'        self.task_progress.emit(self._idx, current, total)\n'
'\n'
'    @Slot(str)\n'
'    def _on_log(self, msg: str):\n'
'        self.task_log.emit(self._idx, msg)\n'
'\n'
'    @Slot(list)\n'
'    def _on_generated(self, paths: list):\n'
'        self._audio_paths = paths\n'
'\n'
'    @Slot(bool, str)\n'
'    def _on_audio_done(self, success: bool, msg: str):\n'
'        task = self.tasks[self._idx]\n'
'        if not success:\n'
'            task.status = "error"\n'
'            self.queue_log.emit("Erro: " + msg)\n'
'            self.task_finished.emit(self._idx, False)\n'
'            self._idx += 1; self._run_current(); return\n'
'        if task.mode in ("audio+video", "audio+video+alt"):\n'
'            self._start_video(task)\n'
'        else:\n'
'            task.status = "done"\n'
'            self.task_finished.emit(self._idx, True)\n'
'            self._idx += 1; self._run_current()\n'
'\n'
'    def _start_video(self, task):\n'
'        from manhwa_app.video_pipeline import VideoPipeline\n'
'        w = self.main_window\n'
'        out_root = w.audio_tab.output_root_edit.text().strip() or "output"\n'
'        if task.mode == "audio+video+alt" and task.img_path:\n'
'            images = sorted(\n'
'                [str(p) for p in Path(task.img_path).glob("*")\n'
'                 if p.suffix.lower() in (".jpg", ".png", ".webp", ".jpeg")],\n'
'                key=natural_sort_key\n'
'            )\n'
'        else:\n'
'            images = w.images_tab.get_images()\n'
'        audios_dir = Path(out_root) / task.project_name / "audios"\n'
'        audios = sorted(\n'
'            [str(p) for p in audios_dir.glob("audio_*.wav")],\n'
'            key=lambda x: int(Path(x).stem.split("_")[1])\n'
'                          if Path(x).stem.split("_")[1].isdigit() else 0\n'
'        )\n'
'        if not (audios and images):\n'
'            self.task_log.emit(self._idx, "Sem audios/imagens para video.")\n'
'            task.status = "done"\n'
'            self.task_finished.emit(self._idx, True)\n'
'            self._idx += 1; self._run_current(); return\n'
'        vcfg = w.video_tab.get_session()\n'
'        pairs = list(zip(audios, images[:len(audios)]))\n'
'        out_vid = str(Path(out_root) / task.project_name / f"{task.project_name}_final.mp4")\n'
'        self._v_pipe = VideoPipeline(\n'
'            pairs=pairs, output_path=out_vid,\n'
'            effect_mode=vcfg.get("effect", "auto"),\n'
'            transition_mode=vcfg.get("transition", "fade"),\n'
'            transition_time=vcfg.get("transition_time", 0.5),\n'
'        )\n'
'        self._v_pipe.log_message.connect(\n'
'            lambda m, i=self._idx: self.task_log.emit(i, m)\n'
'        )\n'
'        self._v_thread = QThread(self)\n'
'        self._v_pipe.moveToThread(self._v_thread)\n'
'        self._v_thread.started.connect(self._v_pipe.run)\n'
'        self._v_pipe.finished.connect(self._on_video_done)\n'
'        self._v_thread.start()\n'
'\n'
'    @Slot(bool, str)\n'
'    def _on_video_done(self, success: bool, msg: str):\n'
'        self._v_thread.quit()\n'
'        task = self.tasks[self._idx]\n'
'        task.status = "done" if success else "error"\n'
'        self.task_finished.emit(self._idx, success)\n'
'        self._idx += 1; self._run_current()\n'
'\n'
'    def _finish(self):\n'
'        self._disconnect_audio()\n'
'        self.queue_log.emit("\\nFila concluida!")\n'
'        self.all_done.emit()\n'
'\n'
'\n'
'# Alias\n'
'QueueOrchestrator = QueueCoordinator\n'
)

src = src[:idx_orch] + NEW_COORD + src[idx_dash_sep:]
print("P2 OK")

# P3
A3 = '    def get_generated_paths(self) -> List[str]:'
assert A3 in src
NEW3 = ('    def configure_and_run_queued(self, task):\n'
'        """Configura AudioTab para tarefa da fila e inicia geracao."""\n'
'        self.project_edit.setText(task.project_name)\n'
'        lang  = task.lang_override  or self.preset_lang_combo.currentText()\n'
'        voice = task.voice_override or ""\n'
'        self._files = [{"path": task.txt_path, "voice": voice, "lang": lang}]\n'
'        self._refresh_list()\n'
'        if task.lang_override:\n'
'            idx = self.preset_lang_combo.findText(task.lang_override)\n'
'            if idx >= 0: self.preset_lang_combo.setCurrentIndex(idx)\n'
'        if task.voice_override:\n'
'            idx = self.preset_voice_combo.findData(task.voice_override)\n'
'            if idx >= 0: self.preset_voice_combo.setCurrentIndex(idx)\n'
'        self._queued_overrides = task\n'
'        self._start_normal()\n'
'\n'
'    def get_generated_paths(self) -> List[str]:\n')
src = src.replace(A3, NEW3, 1)
print("P3 OK")

# P4
P4_OLD = ('        cfg = self._get_tts_config()\n'
          '        \n'
          '        voice_val = self.preset_voice_combo.currentData()\n')
P4_NEW = ('        cfg = self._get_tts_config()\n'
          '\n'
          '        if hasattr(self, "_queued_overrides") and self._queued_overrides:\n'
          '            _ot = self._queued_overrides\n'
          '            if _ot.engine_override:     cfg["tts_engine"] = _ot.engine_override\n'
          '            if _ot.model_type_override: cfg["model_type"] = _ot.model_type_override\n'
          '            self._queued_overrides = None\n'
          '\n'
          '        voice_val = self.preset_voice_combo.currentData()\n')
assert P4_OLD in src; src = src.replace(P4_OLD, P4_NEW, 1); print("P4 OK")

# Save
tmp = tempfile.mktemp(suffix='.py')
with open(tmp, 'w', encoding='utf-8') as f:
    f.write(src)
py_compile.compile(tmp, doraise=True)
shutil.copy(tmp, 'manhwa_app/app.py')
os.unlink(tmp)
print("P1-P4 saved OK")
